### ISSUE TITLE
Specific Tab for a specific user

### ISSUE THREAD

**Issue by Collinsprecious** [nfmohit-wpmudev/bp-custom-menu#6]
Plugin installed and set ✅
Created a tab which URL ✅
Every user have the tab in their profile ✅

Is there a way to say let:
user 1 have this link.... www.user1link.com
User 2 have this link....www.user2link.com

And not all users one link.

Maybe a shortcodes or anything to help

**Comment by nfmohit-wpmudev** [comment]
Hi there, @Collinsprecious!
I hope you are having a great day!

Thank you for your query. Unfortunately, there isn't a way to set up user-specific links for custom menu pages. Could you possibly explain the requirement with user-case scenario and examples so that I can try considering this as a feature request?

Regards,
Nahid

**Comment by nfmohit-wpmudev** [comment]
As this issue has been inactive for a while, I'm going to close it for now. Please reopen if needed. Thanks!
